Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2018-07, with the labels that each got.

#685 Add is_countable to Joomla ruleset
  framework-rulesets/joomla.xml
Labels: PR: quick merge, enhancement

#682 Sniff::getFunctionCallParameters(): correctly handle closures when passed as param
  PHPCompatibility/Sniff.php
  PHPCompatibility/Tests/BaseClass/GetFunctionParametersTest.php
  PHPCompatibility/Tests/sniff-examples/utility-functions/get_function_parameters.php
Labels: PR: quick merge, bug

#670 PHPCSHelper: minor bugfix
  PHPCompatibility/PHPCSHelper.php
Labels: PR: quick merge, bug

#673 Various minor cs fixes
  PHPCompatibility/AbstractNewFeatureSniff.php
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/ConstantArraysUsingDefineSniff.php
  PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/EmptyNonVariableSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
  PHPCompatibility/Sniffs/PHP/InternalInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
  PHPCompatibility/Sniffs/PHP/NewConstantScalarExpressionsSniff.php
  PHPCompatibility/Sniffs/PHP/NewExecutionDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
  PHPCompatibility/Sniffs/PHP/NewLanguageConstructsSniff.php
  PHPCompatibility/Sniffs/PHP/NewTypeCastsSniff.php
  PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
  PHPCompatibility/Sniffs/PHP/OptionalRequiredFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
  PHPCompatibility/Sniffs/PHP/RemovedAlternativePHPTagsSniff.php
  PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/ReservedFunctionNamesSniff.php
  PHPCompatibility/Sniffs/PHP/VariableVariablesSniff.php
  PHPCompatibility/Tests/BaseClass/FunctionsTest.php
  PHPCompatibility/Tests/BaseClass/MethodTestFrame.php
  PHPCompatibility/Tests/BaseClass/TokenScopeTest.php
  PHPCompatibility/Tests/BaseSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/RemovedAlternativePHPTagsSniffTest.php
  phpcs.xml.dist
Labels: PR: quick merge, chores/QA

#671 Remove unused line of code
  PHPCompatibility/Sniff.php
Labels: PR: quick merge, chores/QA

#674 CONTRIBUTING: add note about adding framework ruleset to Travis script
  .github/CONTRIBUTING.md
Labels: PR: quick merge, documentation

#687 PHP 7.3: New `DiscouragedSwitchContinue` sniff
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniffs/PHP/DiscouragedSwitchContinueSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DiscouragedSwitchContinueSniffTest.php
  PHPCompatibility/Tests/sniff-examples/discouraged_switch_continue.php
  composer.json
Labels: enhancement

#690 README: Update minimum PHPCS version requirement and composer install instructions
  README.md
Labels: PR: quick merge, documentation, ready-for-review

#689 Update texts for move to GH organization
  .github/CONTRIBUTING.md
  CHANGELOG.md
  PHPCompatibility/Sniff.php
  PHPCompatibility/Tests/sniff-examples/call_time_pass_by_reference.php
  README.md
  composer.json
Labels: PR: quick merge, PR: ready for review, meta

#693 New sniff to check minimum supported/recommended PHPCS version
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  README.md
Labels: PR: ready for review, chores/QA, documentation

#694 Remove the framework/CMS rulesets
  .github/CONTRIBUTING.md
  .travis.yml
  README.md
  framework-rulesets/joomla.xml
  framework-rulesets/wordpress.xml
Labels: PR: quick merge, PR: ready for review, chores/QA

#675 Changelog for version 8.2.0
  CHANGELOG.md
Labels: PR: ready for review, chores/QA

#696 Changelog: fix a couple of typos
  CHANGELOG.md
Labels: PR: ready for review, documentation

#710 PHP 7.3: RemovedConstants: account for removed global constants
  PHPCompatibility/Sniffs/PHP/RemovedConstantsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/RemovedConstantsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/removed_constants.php
Labels: PR: quick merge, PR: ready for review, enhancement

#707 NewKeyword: bug fix - magic constants are case insensitive
  PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_keywords.php
Labels: PR: quick merge, PR: ready for review, bug

#711 PHP 4.3: new php_uname() $mode parameter
  PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
Labels: bug

#712 Fix PHPUnit 7.2 compatibility
  phpunit-travis.xml
Labels: PR: quick merge, PR: ready for review, chores/QA

#699 Drop support for PHPCS < 2.3.0
  .github/CONTRIBUTING.md
  .travis.yml
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/DiscouragedSwitchContinueSniff.php
  PHPCompatibility/Sniffs/PHP/EmptyNonVariableSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
  PHPCompatibility/Sniffs/PHP/MbstringReplaceEModifierSniff.php
  PHPCompatibility/Sniffs/PHP/NewConstVisibilitySniff.php
  PHPCompatibility/Sniffs/PHP/NewConstantScalarExpressionsSniff.php
  PHPCompatibility/Sniffs/PHP/NewExecutionDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/NewGeneratorReturnSniff.php
  PHPCompatibility/Sniffs/PHP/NewLanguageConstructsSniff.php
  PHPCompatibility/Sniffs/PHP/NewNullableTypesSniff.php
  PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
  PHPCompatibility/Sniffs/PHP/PregReplaceEModifierSniff.php
  PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
  PHPCompatibility/Sniffs/PHP/ReservedFunctionNamesSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  PHPCompatibility/Tests/BaseClass/MethodTestFrame.php
  PHPCompatibility/Tests/BaseClass/TokenScopeTest.php
  PHPCompatibility/Tests/BaseSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/DiscouragedSwitchContinueSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/NewConstantScalarExpressionsSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/NonStaticMagicMethodsSniffTest.php
  PHPCompatibility/Tests/bootstrap.php
  PHPCompatibility/Tests/sniff-examples/utility-functions/token_has_scope.php
  README.md
  phpcs.xml.dist
Labels: PR: high priority, PR: ready for review, chores/QA, phpcs cross-version compat

#706 PHP 7.3: DeprecatedFunctionParameters: account for change to define()
  PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/RemovedFunctionParametersSniffTest.php
  PHPCompatibility/Tests/sniff-examples/removed_function_parameter.php
Labels: PR: quick merge, PR: ready for review, enhancement

#702 PHP 7.3: NewIniDirectives: account for new ini directives
  PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
Labels: PR: quick merge, PR: ready for review, enhancement

#697 PHPCSHelper: minor fix
  PHPCompatibility/PHPCSHelper.php
Labels: PR: quick merge, PR: ready for review

#698 Sniff speed: apply some efficiency fixes
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/ConstantArraysUsingDefineSniff.php
  PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenClosureUseVariableNamesSniff.php
  PHPCompatibility/Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
  PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
  PHPCompatibility/Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
  PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
  PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
Labels: PR: quick merge, PR: ready for review

#677 PHP 7.3: DeprecatedIniDirectives: account for removed ini directives
  PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
Labels: PR: quick merge, PR: ready for review, enhancement

#676 PHP 7.3: NewClasses: account for new CompileError and JsonException
  PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewClassesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_classes.php
Labels: PR: quick merge, PR: ready for review, enhancement

#701 CS: tidy up ruleset
  phpcs.xml.dist
Labels: PR: quick merge, PR: ready for review, chores/QA

#700 CS: remove unnecessary cs-ignore annotations
  PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
  PHPCompatibility/Sniffs/PHP/InternalInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
  PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
  PHPCompatibility/Sniffs/PHP/ReservedFunctionNamesSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#679 PHP 7.3: NewFunctions: account for new functions
  PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_functions.php
Labels: PR: quick merge, PR: ready for review, enhancement

#680 PHP 7.3: RequiredOptionalFunctionParameters: account for change in array_push/unshift()
  PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/RequiredOptionalFunctionParametersSniffTest.php
  PHPCompatibility/Tests/sniff-examples/required_optional_function_parameters.php
Labels: PR: quick merge, PR: ready for review, enhancement

#681 PHP 7.3: DeprecatedFunctions: account for deprecation of image2wbmp()
  PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Labels: PR: quick merge, PR: ready for review, enhancement

#678 PHP 7.3: NewConstants: account for new global constants
  PHPCompatibility/Sniffs/PHP/NewConstantsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewConstantsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_constants.php
Labels: PR: quick merge, PR: ready for review, enhancement

#714 PHP 7.3: DeprecatedFunctions: add deprecation of undocumented Mbstring function aliases
  PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Labels: PR: quick merge, PR: ready for review, enhancement

#715 MbstringReplaceEModifier: also recognize the use of the /e modifier when alias functions are used
  PHPCompatibility/Sniffs/PHP/MbstringReplaceEModifierSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
  PHPCompatibility/Tests/sniff-examples/mbstring_replace_e_modifier.php
Labels: PR: quick merge, PR: ready for review, enhancement

#716 DeprecatedMagicAutoload: minor improvements to the test case file
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedMagicAutoloadSniffTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#717 PHP 7.3: DeprecatedIniDirectives: add deprecation of pdo_odbc.db2_instance_name
  PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
Labels: PR: quick merge, PR: ready for review, enhancement

#719 PHP 7.3: NewIniDirectives: add new syslog.filter
  PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
Labels: PR: quick merge, PR: ready for review, enhancement

#720 PHP 7.3: DeprecatedFunctions: add deprecation of fgetss() and gzgetss() functions
  PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Labels: PR: quick merge, PR: ready for review, enhancement

#661 PHP 4.2/7.0: New sniff to detect passing string literal category to setlocale()
  PHPCompatibility/Sniffs/FunctionParameters/SetlocaleStringSniff.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/SetlocaleStringSniffTest.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/SetlocaleStringTestCases.inc
Labels: enhancement

#654 PHP 7.1: New sniff to detect short list syntax for symmetric array destructuring
  PHPCompatibility/Sniffs/Lists/ShortListSniff.php
  PHPCompatibility/Tests/Sniffs/Lists/ShortListSniffTest.php
  PHPCompatibility/Tests/Sniffs/Lists/ShortListTestCases.inc
Labels: enhancement

#658 New sniff to detect new modes available to fopen()
  PHPCompatibility/Sniffs/FunctionParameters/FopenModeSniff.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/FopenModeSniffTest.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/FopenModeTestCases.inc
Labels: enhancement

#659 PHP 7.2: New sniff to detect passing `null` to get_class()
  PHPCompatibility/Sniffs/FunctionParameters/GetClassNullSniff.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/GetClassNullSniffTest.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/GetClassNullTestCases.inc
Labels: enhancement

#663 PHP 7.2: New sniff to detect usage of non-cryptographic hashes
  PHPCompatibility/Sniffs/FunctionParameters/NonCryptoHashSniff.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/NonCryptoHashSniffTest.php
  PHPCompatibility/Tests/Sniffs/FunctionParameters/NonCryptoHashTestCases.inc
Labels: enhancement
