Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2018-10, with the labels that each got.

#739 Updated authors in composer.json
  composer.json
Labels: PR: quick merge, PR: ready for review, documentation

#741 Changelog and other documentation updates for version 9.0.0
  .gitattributes
  .github/CONTRIBUTING.md
  .gitignore
  CHANGELOG.md
  README.md
  composer.json
Labels: PR: ready for review, documentation

#745 NewFlexibleHeredocNowdoc: remove unused statement
  PHPCompatibility/Sniffs/Syntax/NewFlexibleHeredocNowdocSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#752 PHP 7.3: NewConstants: account for new global Curl constants
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#753 NewClasses: Add com_exception; get versions from php-src tags
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug

#757 PHPCSAliases: update the documentation for the autoloader
  PHPCSAliases.php
Labels: PR: quick merge, PR: ready for review, documentation
