Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2018-03, with the labels that each got.

#594 DeprecatedNewReference: "removed" not forbidden
  PHPCompatibility/Sniffs/PHP/DeprecatedNewReferenceSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/DeprecatedNewReferenceSniffTest.php
Labels: chores/QA

#595 NewScalarTypeDeclarations: fix incorrect results
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_scalar_type_declarations.php
Labels: bug, enhancement

#606 NewFunctions: add PHP 5.6 `pg_lo_truncate()`
  PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_functions.php
Labels: enhancement

#604 Composer: reorganize file
  composer.json
Labels: chores/QA, documentation

#605 PHP 5.6: throw a warning when a call to crypt() is missing $salt
  PHPCompatibility/Sniffs/PHP/OptionalRequiredFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/OptionalRequiredFunctionParametersSniffTest.php
  PHPCompatibility/Tests/sniff-examples/optional_required_function_parameters.php
Labels: enhancement

#609 README: remove PHP "not tested" badge
  README.md
Labels: documentation

#602 Add more new function parameters
  PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_function_parameter.php
Labels: enhancement

#598 PHP 7.3: the `scale` parameter of bcscale() is now optional
  PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/RequiredOptionalFunctionParametersSniffTest.php
  PHPCompatibility/Tests/sniff-examples/required_optional_function_parameters.php
Labels: enhancement

#599 PHP 7.1: detect newly added hash algorithms
  PHPCompatibility/Sniffs/PHP/NewHashAlgorithmsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewHashAlgorithmsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_hash_algorithms.php
Labels: enhancement

#607 Readme: add note about command-line vs ruleset
  README.md
Labels: documentation

#613 Move duplicate PHPCS methods to helper class
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenClosureUseVariableNamesSniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
  PHPCompatibility/Sniffs/PHP/InternalInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/PHP/NewNullableTypesSniff.php
  PHPCompatibility/Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
  PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
Labels: chores/QA, meta

#610 Sniff: add three utility methods to handle number recognition
  PHPCompatibility/Sniff.php
  PHPCompatibility/Tests/BaseClass/IsNumberTest.php
  PHPCompatibility/Tests/BaseClass/TestHelperPHPCompatibility.php
  PHPCompatibility/Tests/sniff-examples/utility-functions/is_number.php
Labels: enhancement

#615 Add a WordPress specific PHPCompatibility ruleset
  .github/CONTRIBUTING.md
  README.md
  framework-rulesets/wordpress.xml
Labels: documentation, enhancement

#620 CS: clean up `generate-forbidden-names-test-files` file
  bin/generate-forbidden-names-test-files
Labels: chores/QA

#616 Composer: allow for PHPUnit 7.x
  composer.json
Labels: chores/QA, documentation

#618 PHP 7.0: New sniff to detect generator return expressions
  PHPCompatibility/Sniffs/PHP/NewGeneratorReturnSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewGeneratorReturnSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_generator_return.php
Labels: enhancement

#577 NewNullableTypes: make the return type part of the sniff more code style independent
  PHPCompatibility/Sniffs/PHP/NewNullableTypesSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewNullableTypesSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_nullable_types.php
Labels: bug, chores/QA

#623 Travis: stop testing on HHVM
  .travis.yml
  PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
Labels: chores/QA

#614 ForbiddenNegativeBitshift: fix false positive and underreporting
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/ForbiddenNegativeBitshiftSniffTest.php
  PHPCompatibility/Tests/sniff-examples/forbidden_negative_bitshift.php
Labels: bug

#628 README: remove VersionEye badge
  README.md
Labels: chores/QA, documentation

#600 PHP 7.2: New PCRENewModifiers sniff
  PHPCompatibility/Sniffs/PHP/PCRENewModifiersSniff.php
  PHPCompatibility/Sniffs/PHP/PregReplaceEModifierSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/PCRENewModifiersSniffTest.php
  PHPCompatibility/Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
  PHPCompatibility/Tests/sniff-examples/pcre_new_modifiers.php
Labels: enhancement

#624 Add base ruleset for Joomla
  framework-rulesets/joomla.xml
Labels: documentation, enhancement

#621 Travis/CS/QA: lint CMS/framework ruleset and check codestyle
  .travis.yml
Labels: chores/QA

#631 Build/Travis: add the Joomla ruleset to the XML CS build check
  .travis.yml
Labels: chores/QA

#630 Minor performance optimization
  PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
Labels: chores/QA

#627 NewKeywords: fix too aggressive accounting for PHPCS cross-compat
  PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
  PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
  PHPCompatibility/Tests/sniff-examples/new_keywords.php
Labels: bug
