Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2019-12, with the labels that each got.

#935 Travis: don't allow PHP 7.4 build to fail
  .travis.yml
  README.md
Labels: PR: quick merge, PR: ready for review, chores/QA

#937 Fix typo
  README.md
Labels: PR: quick merge, PR: ready for review, documentation

#938 Travis: test against PHP 7.4, not snapshot
  .travis.yml
Labels: PR: quick merge, PR: ready for review, chores/QA

#941 Documentation: improve the utility test class descriptions
  PHPCompatibility/Util/Tests/Core/DoesFunctionCallHaveParametersUnitTest.php
  PHPCompatibility/Util/Tests/Core/FunctionsUnitTest.php
  PHPCompatibility/Util/Tests/Core/GetFQClassNameFromDoubleColonTokenUnitTest.php
  PHPCompatibility/Util/Tests/Core/GetFQClassNameFromNewTokenUnitTest.php
  PHPCompatibility/Util/Tests/Core/GetFQExtendedClassNameUnitTest.php
  PHPCompatibility/Util/Tests/Core/GetFunctionParameterCountUnitTest.php
  PHPCompatibility/Util/Tests/Core/GetFunctionParametersUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsClassConstantUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsClassPropertyUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsNumberUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsNumericCalculationUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsShortListUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsUseOfGlobalConstantUnitTest.php
  PHPCompatibility/Util/Tests/Core/TokenScopeUnitTest.php
  PHPCompatibility/Util/Tests/CoreMethodTestFrame.php
  PHPCompatibility/Util/Tests/TestHelperPHPCompatibility.php
Labels: PR: quick merge, PR: ready for review, chores/QA, documentation

#942 NewInterfaces: update reference URLs
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#943 Documentation: add @since tags to file docblocks
  PHPCSAliases.php
  bin/generate-forbidden-names-test-files
  phpunit-bootstrap.php
Labels: PR: quick merge, PR: ready for review, chores/QA, documentation

#945 NewClasses: minor bug fix - move two classes
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug

#948 CS: minor tweaks
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#949 PHP 7.4: Add detection of features from the new FFI extension detection
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#950 Documentation: improve use of `@internal` tags
  PHPCSAliases.php
  PHPCompatibility/PHPCSHelper.php
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParameterShadowSuperGlobalsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewNullableTypesSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/ReservedFunctionNamesSniff.php
  PHPCompatibility/Sniffs/FunctionUse/ArgumentFunctionsReportCurrentValueSniff.php
  PHPCompatibility/Sniffs/Miscellaneous/NewPHPOpenTagEOFSniff.php
  PHPCompatibility/Sniffs/Miscellaneous/RemovedAlternativePHPTagsSniff.php
  PHPCompatibility/Sniffs/Operators/ForbiddenNegativeBitshiftSniff.php
  PHPCompatibility/Sniffs/Operators/NewOperatorsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedIconvEncodingSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedPCREModifiersSniff.php
  PHPCompatibility/Sniffs/Syntax/NewArrayStringDereferencingSniff.php
  PHPCompatibility/Sniffs/Syntax/NewClassMemberAccessSniff.php
  PHPCompatibility/Sniffs/Syntax/NewFunctionArrayDereferencingSniff.php
  PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
  PHPCompatibility/Sniffs/Variables/ForbiddenThisUseContextsSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
  PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.php
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.php
  PHPCompatibility/Util/Tests/Core/IsNumberUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA, documentation

#951 Documentation: various minor tweaks
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParametersWithSameNameSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedMagicAutoloadSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedNamespacedAssertSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionParametersSniff.php
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedMagicAutoloadUnitTest.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.php
Labels: PR: quick merge, PR: ready for review, documentation

#952 .gitattributes: treat the test case files same as PHP files
  .gitattributes
Labels: PR: quick merge, PR: ready for review, chores/QA

#953 Changelog for PHPCompatibility 9.3.5
  CHANGELOG.md
Labels: PR: quick merge, PR: ready for review, meta

#955 Readme: fix "unstable" badge
  README.md
Labels: PR: quick merge, PR: ready for review, documentation
