Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2019-09, with the labels that each got.

#898 Various minor documentation fixes
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/FunctionUse/ArgumentFunctionsUsageSniff.php
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Sniffs/Operators/NewOperatorsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedMbstringModifiersSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedPCREModifiersSniff.php
  PHPCompatibility/Tests/Classes/ForbiddenAbstractPrivateMethodsUnitTest.php
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.3.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.4.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.5.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.6.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.7.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.8.inc
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.9.inc
Labels: PR: quick merge, PR: ready for review, chores/QA

#897 Documentation: add missing @throws tags
  PHPCompatibility/Sniff.php
  PHPCompatibility/Tests/BaseSniffTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#896 Documentation: fix up some @internal tags
  PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
  PHPCompatibility/Sniffs/Syntax/NewArrayStringDereferencingSniff.php
  PHPCompatibility/Sniffs/Syntax/NewClassMemberAccessSniff.php
  PHPCompatibility/Sniffs/Syntax/NewFunctionArrayDereferencingSniff.php
  PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#895 Documentation: fix incorrect @return type
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#892 Documentation: fix incorrect property @var tag types
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Sniffs/ControlStructures/NewExecutionDirectivesSniff.php
  PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewParamTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewReturnTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/NewMagicMethodsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Sniffs/LanguageConstructs/NewLanguageConstructsSniff.php
  PHPCompatibility/Sniffs/Operators/NewOperatorsSniff.php
  PHPCompatibility/Sniffs/TypeCasts/NewTypeCastsSniff.php
  PHPCompatibility/Sniffs/TypeCasts/RemovedTypeCastsSniff.php
  PHPCompatibility/Sniffs/Variables/RemovedPredefinedGlobalVariablesSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#899 Documentation: add docblocks to class constants
  PHPCompatibility/Sniff.php
  PHPCompatibility/Tests/BaseSniffTest.php
  PHPCompatibility/Tests/ControlStructures/ForbiddenBreakContinueVariableArgumentsUnitTest.php
  PHPCompatibility/Tests/FunctionDeclarations/ForbiddenVariableNamesInClosureUseUnitTest.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedMagicAutoloadUnitTest.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.php
  PHPCompatibility/Tests/Miscellaneous/NewPHPOpenTagEOFUnitTest.php
  PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#891 RemovedImplodeFlexibleParamOrder: fix two bugs + one enhancement
  PHPCompatibility/Sniffs/ParameterValues/RemovedImplodeFlexibleParamOrderSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug, enhancement

#893 Travis: update stage conditions
  .travis.yml
Labels: PR: high priority, PR: quick merge, PR: ready for review, chores/QA

#901 Changelog for PHPCompatibility 9.3.1
  CHANGELOG.md
Labels: PR: ready for review, documentation, meta

#904 Updated contribution documentation + Removed WPEngine logo
  .github/CONTRIBUTING.md
  README.md
Labels: PR: quick merge, documentation

#905 Readme: add table of contents
  README.md
Labels: PR: quick merge, PR: ready for review, documentation
