Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2019-11, with the labels that each got.

#923 ForbiddenNames: Add missing reserved keywords to ForbiddenNames sniff
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-extends.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-final-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-private-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-protected-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-public-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-function.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/define.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/function-declare-reference.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/function-declare.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/interface-extends.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/interface.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/method-declare.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/namespace.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/nested-namespace.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/trait.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use-as.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use.php
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.inc
  bin/generate-forbidden-names-test-files
Labels: enhancement

#924 NewConstants: account for yet more undocumented Sodium constants
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#921 RemovedPHP4StyleConstructors: should not apply to interfaces
  PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug

#925 Changelog for PHPCompatibility 9.3.3
  CHANGELOG.md
Labels: PR: quick merge, PR: ready for review, documentation, meta

#926 Release PHPCompatibility 9.3.3
  CHANGELOG.md
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-extends.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-final-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-private-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-protected-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-public-method.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-function.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/const.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/define.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/function-declare-reference.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/function-declare.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/interface-extends.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/interface.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/method-declare.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/namespace.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/nested-namespace.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/trait.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use-as.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use.php
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.inc
  bin/generate-forbidden-names-test-files
Labels: PR: ready for review, meta

#930 ForbiddenNames: allow for `foreach( ... as list() ) {}`
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.inc
Labels: PR: high priority, PR: quick merge, PR: ready for review, bug

#931 Changelog for PHPCompatibility 9.3.4
  CHANGELOG.md
Labels: PR: quick merge, PR: ready for review, documentation

#933 Release PHPCompatibility 9.3.4
  CHANGELOG.md
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.inc
Labels: PR: ready for review, meta

#934 NewShortArray: improve error message
  PHPCompatibility/Sniffs/Syntax/NewShortArraySniff.php
  PHPCompatibility/Tests/Syntax/NewShortArrayUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA
