Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2020-12, with the labels that each got.

#1245 Composer: only allow tagged releases of PHPCSUtils
  .travis.yml
  composer.json
  phpunit-bootstrap.php
Labels: PR: high priority, PR: quick merge, PR: ready for review, chores/QA

#1246 PHP 8.0: NewClasses: add yet more new classes
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Classes/RemovedClassesSniff.php
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#1247 PHP 8.0: RemovedFunctions: account for two more deprecated functions
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#1248 PHP 8.0: NewConstants: add some more new constants
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: PR: quick merge, PR: ready for review, enhancement

#1249 NewConstantArraysUsingDefine: add support for named parameters
  PHPCompatibility/Sniffs/InitialValue/NewConstantArraysUsingDefineSniff.php
Labels: PR: quick merge, PR: ready for review, enhancement

#1255 RemovedImplodeFlexibleParamOrder: use `BCTokens::textStringTokens()`
  PHPCompatibility/Sniffs/ParameterValues/RemovedImplodeFlexibleParamOrderSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1251 Ini sniffs: move `$iniFunctions` property to sniffs
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1252 New DisableSniffMsgTrait
  PHPCompatibility/Helpers/DisableSniffMsgTrait.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
  PHPCompatibility/Util/Tests/Helpers/DisableSniffMsgTraitUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/DisableSniffMsgTraitUnitTest.php
Labels: PR: ready for review, chores/QA

#1254 RemovedIconvEncoding: cleaner error output
  PHPCompatibility/Sniffs/ParameterValues/RemovedIconvEncodingSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1257 RemovedNonCryptoHash: improve comment tolerance
  PHPCompatibility/Sniffs/ParameterValues/RemovedNonCryptoHashSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedNonCryptoHashUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedNonCryptoHashUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug, chores/QA

#1256 RemovedMbStrrposEncodingThirdParam: use `BCTokens::textStringTokens()`
  PHPCompatibility/Sniffs/ParameterValues/RemovedMbStrrposEncodingThirdParamSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1258 RemovedSetlocaleString: tweaks using PHPCSUtils
  PHPCompatibility/Sniffs/ParameterValues/RemovedSetlocaleStringSniff.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1260 CI: switch to GitHub Actions
  .coveralls.yml
  .gitattributes
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  composer.json
Labels: PR: high priority, PR: ready for review, chores/QA

#1253 NewConstantArraysUsingDefine: further implementation of PHPCSUtils
  PHPCompatibility/Sniffs/InitialValue/NewConstantArraysUsingDefineSniff.php
  PHPCompatibility/Tests/InitialValue/NewConstantArraysUsingDefineUnitTest.inc
  PHPCompatibility/Tests/InitialValue/NewConstantArraysUsingDefineUnitTest.php
Labels: PR: quick merge, PR: ready for review, bug

#1242 PHP 8.0 | New `PHPCompatibility.Syntax.InterpolatedStringDereferencing` sniff
  PHPCompatibility/Sniffs/Syntax/NewInterpolatedStringDereferencingSniff.php
  PHPCompatibility/Tests/Syntax/NewInterpolatedStringDereferencingUnitTest.inc
  PHPCompatibility/Tests/Syntax/NewInterpolatedStringDereferencingUnitTest.php
Labels: enhancement

#1262 PHP 8.0: NewNestedStaticAccess: add support for class constant dereferencing
  PHPCompatibility/Sniffs/Syntax/NewNestedStaticAccessSniff.php
  PHPCompatibility/Tests/Syntax/NewNestedStaticAccessUnitTest.inc
  PHPCompatibility/Tests/Syntax/NewNestedStaticAccessUnitTest.php
Labels: enhancement
