Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2021-02, with the labels that each got.

#1250 New HashAlgorithmsTrait, including implementation
  PHPCompatibility/Helpers/HashAlgorithmsTrait.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewHashAlgorithmsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedHashAlgorithmsSniff.php
  PHPCompatibility/Tests/ParameterValues/NewHashAlgorithmsUnitTest.php
  PHPCompatibility/Tests/ParameterValues/RemovedHashAlgorithmsUnitTest.php
Labels: PR: quick merge, PR: ready for review, chores/QA

#1259 NewInterfaces: various bugfixes and enhancements with PHPCSUtils
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: PR: ready for review, bug, enhancement

#1261 New/RemovedPCREModifiers: decouple the sniffs, introduce `PCRERegexTrait` and implement PHPCSUtils
  PHPCompatibility/Helpers/PCRERegexTrait.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewPCREModifiersSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedPCREModifiersSniff.php
  PHPCompatibility/Tests/ParameterValues/NewPCREModifiersUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/NewPCREModifiersUnitTest.php
  PHPCompatibility/Tests/ParameterValues/RemovedPCREModifiersUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedPCREModifiersUnitTest.php
Labels: PR: ready for review, chores/QA, enhancement

#1266 Point broken links to legacy docs
  PHPCompatibility/Sniffs/ControlStructures/ForbiddenBreakContinueVariableArgumentsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParameterShadowSuperGlobalsSniff.php
Labels: PR: quick merge, chores/QA, documentation

#1268 GH Actions tweaks
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: PR: quick merge, PR: ready for review, chores/QA

#1264 Contributing: add links to PHP 4 and PHP 5 documentation
  .github/CONTRIBUTING.md
Labels: PR: quick merge, PR: ready for review, documentation

#1270 Adding Moodle's codechecker to extending projects
  README.md
Labels: documentation

#1271 GH Actions: show CS and linting results inline in the PR
  .github/workflows/basics.yml
  .github/workflows/test.yml
Labels: PR: quick merge, PR: ready for review, chores/QA
