Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2022-12, with the labels that each got.

#1407 PHP 8.1 | ForbiddenNames: detect reserved keywords used as name for an enum
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/enum-backed.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/enum.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.2.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.php
  bin/generate-forbidden-names-test-files
Labels: enhancement, PR: quick merge, PR: ready for review

#1406 Refactor complex version-list based sniffs
  PHPCompatibility/AbstractComplexVersionSniff.php
  PHPCompatibility/AbstractNewFeatureSniff.php
  PHPCompatibility/AbstractRemovedFeatureSniff.php
  PHPCompatibility/ComplexVersionInterface.php
  PHPCompatibility/Helpers/ComplexVersionDeprecatedRemovedFeatureTrait.php
  PHPCompatibility/Helpers/ComplexVersionNewFeatureTrait.php
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Classes/NewTypedPropertiesSniff.php
  PHPCompatibility/Sniffs/Classes/RemovedClassesSniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Sniffs/ControlStructures/NewExecutionDirectivesSniff.php
  PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewParamTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewReturnTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/FunctionNameRestrictions/NewMagicMethodsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionParametersSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Sniffs/LanguageConstructs/NewLanguageConstructsSniff.php
  PHPCompatibility/Sniffs/Operators/NewOperatorsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewHashAlgorithmsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedHashAlgorithmsSniff.php
  PHPCompatibility/Sniffs/TypeCasts/NewTypeCastsSniff.php
  PHPCompatibility/Sniffs/TypeCasts/RemovedTypeCastsSniff.php
  PHPCompatibility/Sniffs/Variables/RemovedPredefinedGlobalVariablesSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/NewReturnTypeDeclarationsUnitTest.php
  PHPCompatibility/Tests/ParameterValues/NewHashAlgorithmsUnitTest.php
  PHPCompatibility/Util/Tests/Helpers/ComplexVersionDeprecatedRemovedFeatureTraitUnitTest.php
  PHPCompatibility/Util/Tests/Helpers/ComplexVersionNewFeatureTraitUnitTest.php
Labels: enhancement, breaking change, meta, PR: ready for review

#1415 PHP 8.0/8.1 | ForbiddenNames: detect use of new keywords when used as names
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-const.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class-use-trait-alias-method.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/class.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/const.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/define.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/enum-backed.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/enum.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/function-declare.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/group-use-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/group-use-const-as-in-group.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/group-use-const-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/group-use-function-as-in-group.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/group-use-function-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/interface.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/method-declare.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/multi-use-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/multi-use-const-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/multi-use-function-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/namespace.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/nested-namespace.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/trait.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use-const-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNames/use-function-as.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.1.inc
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.php
  bin/generate-forbidden-names-test-files
Labels: enhancement, PR: quick merge, PR: ready for review

#1416 NewExecutionDirectives: various bug fixes
  PHPCompatibility/Sniffs/ControlStructures/NewExecutionDirectivesSniff.php
  PHPCompatibility/Tests/ControlStructures/NewExecutionDirectivesUnitTest.inc
  PHPCompatibility/Tests/ControlStructures/NewExecutionDirectivesUnitTest.php
Labels: bug, enhancement, PR: quick merge, PR: ready for review

#1417 :sparkles: PHP 8.0: New `PHPCompatibility.Classes.NewConstructorPropertyPromotion` sniff
  PHPCompatibility/Docs/Classes/NewConstructorPropertyPromotionStandard.xml
  PHPCompatibility/Sniffs/Classes/NewConstructorPropertyPromotionSniff.php
  PHPCompatibility/Tests/Classes/NewConstructorPropertyPromotionUnitTest.inc
  PHPCompatibility/Tests/Classes/NewConstructorPropertyPromotionUnitTest.php
Labels: enhancement, PR: ready for review

#1418 :sparkles: PHP 8.1: New `PHPCompatibility.ParameterValues.RemovedVersionCompareOperators` sniff
  PHPCompatibility/Docs/ParameterValues/RemovedVersionCompareOperatorsStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/RemovedVersionCompareOperatorsSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedVersionCompareOperatorsUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedVersionCompareOperatorsUnitTest.php
Labels: enhancement, PR: ready for review

#1419 :sparkles: PHP 8.1: New `PHPCompatibility.ParameterValues.NewHTMLEntitiesFlagsDefault` sniff
  PHPCompatibility/Docs/ParameterValues/NewHTMLEntitiesFlagsDefaultStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/NewHTMLEntitiesFlagsDefaultSniff.php
  PHPCompatibility/Tests/ParameterValues/NewHTMLEntitiesFlagsDefaultUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/NewHTMLEntitiesFlagsDefaultUnitTest.php
Labels: enhancement, PR: ready for review

#1420 :sparkles: PHP 8.1 | New `PHPCompatibility.Numbers.NewExplicitOctalNotation` sniff
  PHPCompatibility/Docs/Numbers/NewExplicitOctalNotationStandard.xml
  PHPCompatibility/Sniffs/Numbers/NewExplicitOctalNotationSniff.php
  PHPCompatibility/Tests/Numbers/NewExplicitOctalNotationUnitTest.inc
  PHPCompatibility/Tests/Numbers/NewExplicitOctalNotationUnitTest.php
Labels: enhancement, PR: ready for review

#1421 NewNumericLiteralSeparator: add test with explicit octal notation
  PHPCompatibility/Tests/Numbers/NewNumericLiteralSeparatorUnitTest.inc
  PHPCompatibility/Tests/Numbers/NewNumericLiteralSeparatorUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1422 Numbers/ValidIntegers: account for PHP 8.1 explicit octal notation
  PHPCompatibility/Sniffs/Numbers/ValidIntegersSniff.php
  PHPCompatibility/Tests/Numbers/ValidIntegersUnitTest.inc
  PHPCompatibility/Tests/Numbers/ValidIntegersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1423 :sparkles: PHP 8.0 | New `NewNamedParametersSniff` sniff
  PHPCompatibility/Sniffs/FunctionUse/NewNamedParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/NewNamedParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewNamedParametersUnitTest.php
Labels: enhancement, PR: ready for review

#1424 :sparkles: PHP 8.2 | New `PHPCompatibility.TextStrings.RemovedDollarBraceStringEmbeds` sniff
  PHPCompatibility/Docs/TextStrings/RemovedDollarBraceStringEmbedsStandard.xml
  PHPCompatibility/Sniffs/TextStrings/RemovedDollarBraceStringEmbedsSniff.php
  PHPCompatibility/Tests/TextStrings/RemovedDollarBraceStringEmbedsUnitTest.1.inc
  PHPCompatibility/Tests/TextStrings/RemovedDollarBraceStringEmbedsUnitTest.2.inc
  PHPCompatibility/Tests/TextStrings/RemovedDollarBraceStringEmbedsUnitTest.php
Labels: enhancement, PR: ready for review

#1425 :sparkles: PHP 8.1: New `PHPCompatibility.Syntax.NewFirstClassCallables` sniff
  PHPCompatibility/Docs/Syntax/NewFirstClassCallablesStandard.xml
  PHPCompatibility/Sniffs/Syntax/NewFirstClassCallablesSniff.php
  PHPCompatibility/Tests/Syntax/NewFirstClassCallablesUnitTest.inc
  PHPCompatibility/Tests/Syntax/NewFirstClassCallablesUnitTest.php
Labels: enhancement, PR: ready for review

#1426 :sparkles: PHP 8.1: New `PHPCompatibility.Classes.NewReadonlyProperties` sniff
  PHPCompatibility/Docs/Classes/NewReadonlyPropertiesStandard.xml
  PHPCompatibility/Sniffs/Classes/NewReadonlyPropertiesSniff.php
  PHPCompatibility/Tests/Classes/NewReadonlyPropertiesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewReadonlyPropertiesUnitTest.php
Labels: enhancement, PR: ready for review

#1414 Add Github Action link
  README.md
Labels: documentation

#1427 QA: don't use reserved keywords as parameter names
  PHPCSAliases.php
  PHPCompatibility/Tests/ParameterValues/NewHTMLEntitiesEncodingDefaultUnitTest.php
  PHPCompatibility/Tests/ParameterValues/NewIDNVariantDefaultUnitTest.php
  PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.php
  PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1428 ForbiddenNames: use `code` not `type`
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1429 Sniff:: remove the `inClassScope()` method
  PHPCompatibility/Sniff.php
  PHPCompatibility/Util/Tests/Core/TokenScopeUnitTest.inc
  PHPCompatibility/Util/Tests/Core/TokenScopeUnitTest.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review

#1433 RemovedFunctionParameters: add support for named parameters
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1432 NewFunctionParameters: add support for named parameters + bug fix
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.php
Labels: bug, enhancement, chores/QA, PR: quick merge, PR: ready for review

#1431 RequiredToOptionalFunctionParameters: add support for named parameters
  PHPCompatibility/Sniffs/FunctionUse/RequiredToOptionalFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/RequiredToOptionalFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RequiredToOptionalFunctionParametersUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1430 OptionalToRequiredFunctionParameters: add support for named parameters + bug fix
  PHPCompatibility/Sniffs/FunctionUse/OptionalToRequiredFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/OptionalToRequiredFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/OptionalToRequiredFunctionParametersUnitTest.php
Labels: bug, enhancement, chores/QA, PR: quick merge, PR: ready for review

#1436 GH Actions: tweak php versions and more / PHP 8.2 not allowed to fail
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1438 Link to legacy docs
  PHPCompatibility/Sniffs/Keywords/CaseSensitiveKeywordsSniff.php
Labels: chores/QA, documentation

#1439 Sniff::isUseOfGlobalConstant(): various improvements and PHP 8.0+ support
  PHPCompatibility/Sniff.php
  PHPCompatibility/Util/Tests/Core/IsUseOfGlobalConstantUnitTest.inc
  PHPCompatibility/Util/Tests/Core/IsUseOfGlobalConstantUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1442 .gitattributes: exclude test bootstrap from dist package
  .gitattributes
Labels: chores/QA, PR: quick merge, PR: ready for review

#1443 PHP 8.2 | New `PHPCompatibility.Constants.NewConstantsInTraits` sniff
  PHPCompatibility/Docs/Constants/NewConstantsInTraitsStandard.xml
  PHPCompatibility/Sniffs/Constants/NewConstantsInTraitsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsInTraitsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsInTraitsUnitTest.php
Labels: enhancement, PR: ready for review

#1444 PHP 8.0 | Add support for and detection of union types in param, return and property types
  PHPCompatibility/Sniffs/Classes/NewTypedPropertiesSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewParamTypeDeclarationsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewReturnTypeDeclarationsSniff.php
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
  PHPCompatibility/Tests/FunctionDeclarations/NewParamTypeDeclarationsUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NewParamTypeDeclarationsUnitTest.php
  PHPCompatibility/Tests/FunctionDeclarations/NewReturnTypeDeclarationsUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NewReturnTypeDeclarationsUnitTest.php
Labels: enhancement, PR: ready for review

#1451 Link to legacy docs
  PHPCompatibility/Sniffs/ParameterValues/ChangedObStartEraseFlagsSniff.php
Labels: documentation

#1455 Old changelog no longer displayed on main site
  PHPCompatibility/Sniffs/ParameterValues/ForbiddenStripTagsSelfClosingXHTMLSniff.php
Labels: documentation

#1445 Various sniffs: remove redundant try/catch
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParameterShadowSuperGlobalsSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParametersWithSameNameSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewNullableTypesSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/RemovedOptionalBeforeRequiredParamSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1446 NewInterfaces: add support for interfaces used in union and intersection types
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1447 PHP 8.0 | TypeDeclaration sniffs: examine properties declared in the constructor correctly
  PHPCompatibility/Sniffs/Classes/NewTypedPropertiesSniff.php
  PHPCompatibility/Sniffs/FunctionDeclarations/NewParamTypeDeclarationsSniff.php
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
  PHPCompatibility/Tests/FunctionDeclarations/NewParamTypeDeclarationsUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NewParamTypeDeclarationsUnitTest.php
Labels: enhancement, chores/QA, PR: ready for review

#1449 PHP 7.4 | Various sniffs: correctly handle arrow functions
  PHPCompatibility/Sniffs/ControlStructures/ForbiddenBreakContinueVariableArgumentsSniff.php
  PHPCompatibility/Sniffs/Syntax/ForbiddenCallTimePassByReferenceSniff.php
  PHPCompatibility/Tests/ControlStructures/ForbiddenBreakContinueVariableArgumentsUnitTest.inc
  PHPCompatibility/Tests/ControlStructures/ForbiddenBreakContinueVariableArgumentsUnitTest.php
  PHPCompatibility/Tests/Syntax/ForbiddenCallTimePassByReferenceUnitTest.inc
  PHPCompatibility/Tests/Syntax/ForbiddenCallTimePassByReferenceUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1453 PHP 8.2 | New `PHPCompatibility.Classes.NewReadonlyClasses` sniff
  PHPCompatibility/Docs/Classes/NewReadonlyClassesStandard.xml
  PHPCompatibility/Sniffs/Classes/NewReadonlyClassesSniff.php
  PHPCompatibility/Tests/Classes/NewReadonlyClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewReadonlyClassesUnitTest.php
Labels: enhancement, PR: ready for review
