Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2023-08, with the labels that each got.

#1584 GH Actions: update for php-coveralls 2.6.0
  .github/workflows/test.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1591 Add more `'extension'` keys to the array based sniffs
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Classes/RemovedClassesSniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1588 ParameterValues/NewIconvMbstringCharsetDefault: fixed various edge cases & improved modern PHP support
  PHPCompatibility/Sniffs/ParameterValues/NewIconvMbstringCharsetDefaultSniff.php
  PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.php
Labels: bug, enhancement, PR: ready for review

#1592 ReservedNames: refactor to allow for detecting more reserved names
  PHPCompatibility/Sniffs/Namespaces/ReservedNamesSniff.php
  PHPCompatibility/Tests/Namespaces/ReservedNamesUnitTest.inc
  PHPCompatibility/Tests/Namespaces/ReservedNamesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1593 Keywords/NewKeywords: merge `NewArrowFunctionSniff`
  PHPCompatibility/Sniffs/FunctionDeclarations/NewArrowFunctionSniff.php
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/NewArrowFunctionUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NewArrowFunctionUnitTest.php
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.inc
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1594 PHP 7.4 | NewIniDirectives: recognize a few more new directives
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1595 PHP 8.0 | NewInterfaces: add support for DOM living standard APIs related interfaces (RFC)
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1587 Simplify logic in unit tests
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: chores/QA

#1596 AbstractFunctionCallParameter: prevent false positives on PHP 8.0+ attributes
  PHPCompatibility/AbstractFunctionCallParameterSniff.php
  PHPCompatibility/Tests/ParameterValues/ForbiddenSessionModuleNameUserUnitTest.1.inc
  PHPCompatibility/Tests/ParameterValues/ForbiddenSessionModuleNameUserUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1597 PHP 8.0 | Keywords/NewKeywords: detect the new `match` keyword (RFC)
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.inc
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1598 PHP 8.0 | NewIniDirectives: recognize JIT related directives (RFC)
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1599 PHP 8.0 | RemovedFunctions: update some previously deprecated to removed
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1600 PHP 8.0 | RemovedConstants: add more removed constants
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1601 PHP 8.1 | NewConstants/NewClasses: add new intersection related constants/classes (RFC)
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1603 PHP 8.1 | RemovedIniDirectives: recognize `mysqlnd.fetch_data_copy`
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1604 PHP 8.1 | Various sniffs: detect enums and enum related features (RFC)
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Sniffs/Interfaces/InternalInterfacesSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.inc
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1605 PHP 8.2 | RemovedFunctions: recognized utf8[en|de]code() as deprecated (RFC)
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1607 PHP 8.2 | NewPCREModifiers: recognize the new "n" modifier
  PHPCompatibility/Sniffs/ParameterValues/NewPCREModifiersSniff.php
  PHPCompatibility/Tests/ParameterValues/NewPCREModifiersUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/NewPCREModifiersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1609 PHP 8.1.2 | NewConstants: handle new `MYSQLI_IS_MARIADB` constant
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1610 PHP 8.2 | Various sniffs: detect the new random extension(RFC)
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Sniffs/Namespaces/ReservedNamesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
  PHPCompatibility/Tests/Namespaces/ReservedNamesUnitTest.inc
  PHPCompatibility/Tests/Namespaces/ReservedNamesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1612 PHP 8.2 | NewFunctions: various updates
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1613 PHP 8.2 | NewIniDirectives: various updates
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1614 PHP 8.3 | :sparkles: New `PHPCompatibility.ParameterValues.RemovedGetClassNoArgs` sniff (RFC)
  PHPCompatibility/Docs/ParameterValues/RemovedGetClassNoArgsStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/RemovedGetClassNoArgsSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedGetClassNoArgsUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedGetClassNoArgsUnitTest.php
Labels: enhancement, PR: ready for review

#1615 PHP 8.3 | :sparkles: New `PHPCompatibility.ParameterValues.RemovedMbStrimWidthNegativeWidth` sniff (RFC)
  PHPCompatibility/Docs/ParameterValues/RemovedMbStrimWidthNegativeWidthStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/RemovedMbStrimWidthNegativeWidthSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedMbStrimWidthNegativeWidthUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedMbStrimWidthNegativeWidthUnitTest.php
Labels: enhancement, PR: ready for review

#1611 PHP 8.2 | RemovedIniDirectives: recognize `mysqli.reconnect`
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1616 PHP 8.2 | NewConstants: various updates
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
Labels: enhancement, PR: ready for review

#1617 PHP 8.2.1 | NewFunctions: detect use of `imap_is_open()`
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1618 PHP 8.3 | Various sniffs: deprecate remains of string evaluated code assertions (RFC)
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1620 PHP 8.3 | :sparkles: New `PHPCompatibility.ParameterValues.RemovedLdapConnectSignatures` sniff (RFC)
  PHPCompatibility/Docs/ParameterValues/RemovedLdapConnectSignaturesStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/RemovedLdapConnectSignaturesSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedLdapConnectSignaturesUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedLdapConnectSignaturesUnitTest.php
Labels: enhancement, PR: ready for review

#1621 PHP 8.3 | NewIniDirectives: various updates
  PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1619 PHP 8.3 | RemovedFunctionParameters: account for signature change for imagerotate()
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1623 PHP 8.3 | RemovedConstants: recognize `MT_RAND_PHP` (RFC)
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1622 PHP 8.3 | NewFunctions: detect use of `json_validate()` (RFC)
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1624 PHP 8.3 | RemovedIniDirectives: recognize `opcache.consistency_checks`
  PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
  PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1625 PHP 8.3 | NewFunctions: detect use of `mb_str_pad()` (RFC)
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1626 PHP 8.3 | NewFunctions: recognize ldap_connect_wallet() and ldap_exop_sync() (RFC)
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1627 PHP 8.3 | RemovedConstants: recognize `U_MULTIPLE_DECIMAL_SEPERATORS`
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1628 PHP 8.3 | NewFunctionParameters: account for signature change for posix_getrlimit()
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1629 Classes/NewFinalConstants: fix documentation
  PHPCompatibility/Docs/Classes/NewFinalConstantsStandard.xml
Labels: chores/QA, documentation, PR: quick merge, PR: ready for review

#1631 PHP 8.3 | NewFunctions: recognize `stream_context_set_options()` (RFC)
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review
