Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2023-03, with the labels that each got.

#1469 Clarify ENT_HTML401 in html* functions
  PHPCompatibility/Sniffs/ParameterValues/NewHTMLEntitiesFlagsDefaultSniff.php
Labels: documentation

#1475 ForbiddenNames: fix bug in enum special casing
  PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
  PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.1.inc
Labels: bug, PR: quick merge, PR: ready for review

#1478 NewKeywords: minor improvement
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.inc
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1479 GH Actions: various minor tweaks
  .github/workflows/test.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1292 [xml doc] RemovedPHP4StyleConstructors
  PHPCompatibility/Docs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsStandard.xml
Labels: documentation

#1293 [xml doc] ReservedFunctionNames
  PHPCompatibility/Docs/FunctionNameRestrictions/ReservedFunctionNamesStandard.xml
Labels: documentation

#1295 [xml doc] RemovedPCREModifiers
  PHPCompatibility/Docs/ParameterValues/RemovedPCREModifiersStandard.xml
Labels: documentation

#1294 [xml doc] ArgumentFunctionsReportCurrentValue
  PHPCompatibility/Docs/FunctionUse/ArgumentFunctionsReportCurrentValueStandard.xml
Labels: documentation
