Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2023-05, with the labels that each got.

#1543 __destruct visibility must not be declared as public
  PHPCompatibility/Sniffs/FunctionDeclarations/NonStaticMagicMethodsSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
Labels: bug

#1545 Tests: improve performance
  PHPCompatibility/Tests/BaseSniffTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1544 Coveralls: use Coveralls specific token
  .github/workflows/test.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1546 Add checklist for XML docs reviews
  .github/XML_docs_review_checklist.md
Labels: chores/QA, PR: quick merge, PR: ready for review

#1547 Composer: tidy up config file
  composer.json
Labels: chores/QA, PR: quick merge, PR: ready for review

#1554 Add `security.md` file
  .github/SECURITY.md
Labels: chores/QA, PR: quick merge, PR: ready for review

#1553 CONTRIBUTING: update info about running PHPCS on this repo
  .github/CONTRIBUTING.md
Labels: chores/QA, documentation, PR: quick merge, PR: ready for review

#1552 TokenGroup::is*Number(): change base TestCase
  PHPCompatibility/Util/Tests/Helpers/TokenGroup/IsNumberUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1551 Sniff::isNamespaced(): remove unused method
  PHPCompatibility/Sniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1550 Upgrade/LowPHP: update the minimum recommended PHP version to 7.2
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1549 Remove the `PHPCompatibility.Upgrade.LowPHPCS` sniff
  PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
  PHPCompatibility/Tests/Upgrade/LowPHPCSUnitTest.inc
  PHPCompatibility/Tests/Upgrade/LowPHPCSUnitTest.php
Labels: breaking change, PR: quick merge, PR: ready for review

#1548 Introduce two `InvalidTestVersion` exceptions
  PHPCompatibility/Exceptions/InvalidTestVersion.php
  PHPCompatibility/Exceptions/InvalidTestVersionRange.php
  PHPCompatibility/Helpers/TestVersionTrait.php
  PHPCompatibility/Util/Tests/Exceptions/InvalidTestVersionRangeUnitTest.php
  PHPCompatibility/Util/Tests/Exceptions/InvalidTestVersionUnitTest.php
  PHPCompatibility/Util/Tests/Helpers/TestVersionTraitUnitTest.php
  phpunit.xml.dist
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1556 DisableSniffMsg: change from trait to class with static method + simplify
  PHPCompatibility/Helpers/DisableSniffMsg.php
  PHPCompatibility/Helpers/DisableSniffMsgTrait.php
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
  PHPCompatibility/Util/Tests/Helpers/DisableSniffMsgTraitUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/DisableSniffMsgUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1557 ScannedCode::getTestVersion(): refactor the code for improved performance
  PHPCompatibility/Helpers/ScannedCode.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1558 FunctionDeclarations/NewTrailingComma: add extra test for edge case
  PHPCompatibility/Tests/FunctionDeclarations/NewTrailingCommaUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NewTrailingCommaUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1559 FunctionDeclarations/NonStaticMagicMethods: test tweaks
  PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1560 FunctionDeclarations/RemovedReturnByReferenceFromVoid: bug fix - type keywords are case in-sensitive + more tests
  PHPCompatibility/Sniffs/FunctionDeclarations/RemovedReturnByReferenceFromVoidSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/RemovedReturnByReferenceFromVoidUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/RemovedReturnByReferenceFromVoidUnitTest.php
Labels: bug, chores/QA, PR: quick merge, PR: ready for review

#1561 FunctionNameRestrictions/NewMagicMethods: minor tweaks + extra tests
  PHPCompatibility/Sniffs/FunctionNameRestrictions/NewMagicMethodsSniff.php
  PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.inc
  PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1562 FunctionNameRestrictions/RemovedNamespacedAssert: add tests with PHP 8.1+ enums
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.1.inc
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.2.inc
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1563 FunctionNameRestrictions/RemovedPHP4StyleConstructors: bow out when testVersion min >= 8.0 + efficiency tweak
  PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.inc
  PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1564 FunctionNameRestrictions/ReservedFunctionNames: support PHP 8.0 attributes and more
  PHPCompatibility/Sniffs/FunctionNameRestrictions/ReservedFunctionNamesSniff.php
  PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.inc
  PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.php
Labels: bug, chores/QA, PR: quick merge, PR: ready for review

#1565 Generators/NewGeneratorReturn: improved false positive prevention/arrow functions
  PHPCompatibility/Sniffs/Generators/NewGeneratorReturnSniff.php
  PHPCompatibility/Tests/Generators/NewGeneratorReturnUnitTest.inc
  PHPCompatibility/Tests/Generators/NewGeneratorReturnUnitTest.php
Labels: bug, enhancement, PR: quick merge, PR: ready for review

#1566 Interfaces/InternalInterfaces: detect interfaces extending + enums implementing
  PHPCompatibility/Sniffs/Interfaces/InternalInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1567 TokenGroup::is*Number(): remove `$supportsPHP5` parameter/use `ScannedCode` directly
  PHPCompatibility/Helpers/TokenGroup.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/InitialValue/NewConstantScalarExpressionsSniff.php
  PHPCompatibility/Sniffs/Operators/ForbiddenNegativeBitshiftSniff.php
  PHPCompatibility/Sniffs/ParameterValues/ChangedObStartEraseFlagsSniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewArrayReduceInitialTypeSniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewNegativeStringOffsetSniff.php
  PHPCompatibility/Util/Tests/Helpers/TokenGroup/IsNumberUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1569 Interfaces/NewInterfaces: detect PHP 8.1+ enums implementing new interfaces and other tweaks
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1568 Sniff: move isNumericCalculation() method to TokenGroup`
  PHPCompatibility/Helpers/TokenGroup.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/ParameterValues/NewArrayReduceInitialTypeSniff.php
  PHPCompatibility/Sniffs/ParameterValues/RemovedMbStrrposEncodingThirdParamSniff.php
  PHPCompatibility/Util/Tests/Helpers/TokenGroup/IsNumericCalculationUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/TokenGroup/IsNumericCalculationUnitTest.php
  PHPCompatibility/Util/Tests/TestHelperPHPCompatibility.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review

#1570 Sniff: move isVariable() method to TokenGroup
  PHPCompatibility/Helpers/TokenGroup.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/ControlStructures/NewForeachExpressionReferencingSniff.php
  PHPCompatibility/Sniffs/LanguageConstructs/NewEmptyNonVariableSniff.php
  PHPCompatibility/Tests/ControlStructures/NewForeachExpressionReferencingUnitTest.php
  PHPCompatibility/Tests/LanguageConstructs/NewEmptyNonVariableUnitTest.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review

#1571 New ResolveHelper class for FQN related methods
  PHPCompatibility/Helpers/ResolveHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/Classes/ForbiddenExtendingFinalPHPClassSniff.php
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Sniffs/Classes/RemovedClassesSniff.php
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQClassNameFromDoubleColonTokenUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQClassNameFromDoubleColonTokenUnitTest.php
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQClassNameFromNewTokenUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQClassNameFromNewTokenUnitTest.php
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQExtendedClassNameUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQExtendedClassNameUnitTest.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review

#1572 New `MiscHelper` class for miscellaneous utility methods
  PHPCompatibility/Helpers/MiscHelper.php
  PHPCompatibility/Sniff.php
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
  PHPCompatibility/Util/Tests/Helpers/MiscHelper/IsUseOfGlobalConstantUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/MiscHelper/IsUseOfGlobalConstantUnitTest.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review

#1573 Interfaces/RemovedSerializable: skip over PHP 8.0+ attributes + detect on PHP 8.1 enums
  PHPCompatibility/Sniffs/Interfaces/RemovedSerializableSniff.php
  PHPCompatibility/Tests/Interfaces/RemovedSerializableUnitTest.inc
  PHPCompatibility/Tests/Interfaces/RemovedSerializableUnitTest.php
Labels: enhancement, chores/QA, PR: quick merge, PR: ready for review

#1574 Tests: remove the `CoreMethodTestFrame` and `TestHelperPHPCompatibility` classes
  PHPCompatibility/Util/Tests/CoreMethodTestFrame.php
  PHPCompatibility/Util/Tests/TestHelperPHPCompatibility.php
  phpunit-bootstrap.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1575 ResolveHelper::getFQExtendedClassName(): stop accepting interface tokens and other tweaks
  PHPCompatibility/Helpers/ResolveHelper.php
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQExtendedClassNameUnitTest.inc
  PHPCompatibility/Util/Tests/Helpers/ResolveHelper/GetFQExtendedClassNameUnitTest.php
Labels: breaking change, chores/QA, PR: quick merge, PR: ready for review
