Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2024-02, with the labels that each got.

#1662 Switch to PHPCSStandards/PHP_CodeSniffer & raise minimum supported version
  .github/CONTRIBUTING.md
  .github/workflows/test.yml
  CHANGELOG.md
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
  README.md
  composer.json
  phpcs.xml.dist
Labels: meta, PR: quick merge, PR: ready for review

#1667 PHP 8.3 | Revert some commits for functionality pulled from PHP 8.3
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.inc
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1668 AbstractFunctionCallParameter: fix copy/pasta
  PHPCompatibility/AbstractFunctionCallParameterSniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1670 Variables/ForbiddenThisUseContexts: fix false positive for $this in unset
  PHPCompatibility/Sniffs/Variables/ForbiddenThisUseContextsSniff.php
  PHPCompatibility/Tests/Variables/ForbiddenThisUseContextsUnitTest.inc
  PHPCompatibility/Tests/Variables/ForbiddenThisUseContextsUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1671 PHP 8.4 | ParameterValues/RemovedLdapConnectSignatures: account for deprecation of three+ param signature (RFC)
  PHPCompatibility/Docs/ParameterValues/RemovedLdapConnectSignaturesStandard.xml
  PHPCompatibility/Sniffs/ParameterValues/RemovedLdapConnectSignaturesSniff.php
  PHPCompatibility/Tests/ParameterValues/RemovedLdapConnectSignaturesUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/RemovedLdapConnectSignaturesUnitTest.php
Labels: enhancement, PR: ready for review

#1673 PHP 8.4 | RemovedFunctionParameters: account for deprecation of overloaded ldap_exop() signature (RFC)
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1674 PHP 8.4 | RemovedFunctions: account for deprecation of intlcal_set() (RFC)
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1672 PHP 8.4 | OptionalToRequiredFunctionParameters: account for deprecation of overloaded stream_context_set_option() signature (RFC)
  PHPCompatibility/Sniffs/FunctionUse/OptionalToRequiredFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/OptionalToRequiredFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/OptionalToRequiredFunctionParametersUnitTest.php
Labels: enhancement, PR: ready for review

#1676 PHP 8.4 | RemovedFunctions: account for deprecation of intlgregcal_create_instance() (RFC)
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1677 PHP 8.4 | RemovedFunctionParameters: account for deprecation of overloaded session_set_save_handler() signature (RFC)
  PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1586 Create special case for T_BAD_CHARACTER constant
  PHPCompatibility/Sniffs/Constants/NewConstantsSniff.php
  PHPCompatibility/Sniffs/Constants/RemovedConstantsSniff.php
  PHPCompatibility/Tests/Constants/NewConstantsUnitTest.php
  PHPCompatibility/Tests/Constants/RemovedConstantsUnitTest.php
Labels: enhancement
