Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2024-04, with the labels that each got.

#1697 NewFlexibleHeredocNowdoc: fix incorrect error code
  PHPCompatibility/Sniffs/Syntax/NewFlexibleHeredocNowdocSniff.php
Labels: bug, PR: quick merge, PR: ready for review

#1699 PHP 8.4 | FunctionDeclarations/RemovedOptionalBeforeRequiredParam: flag implicitly nullable parameters
  PHPCompatibility/Docs/FunctionDeclarations/RemovedOptionalBeforeRequiredParamStandard.xml
  PHPCompatibility/Sniffs/FunctionDeclarations/RemovedOptionalBeforeRequiredParamSniff.php
  PHPCompatibility/Tests/FunctionDeclarations/RemovedOptionalBeforeRequiredParamUnitTest.inc
  PHPCompatibility/Tests/FunctionDeclarations/RemovedOptionalBeforeRequiredParamUnitTest.php
Labels: enhancement, PR: ready for review

#1695 NewClassesSniff incorrectly reports imported classes as missing
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
  PHPCompatibility/Tests/Classes/NewClassesUsesNoLeakUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUsesUnitTest.inc
Labels: enhancement

#1701 FunctionDeclarations/NewReturnTypeDeclarations: minor clean up
  PHPCompatibility/Tests/FunctionDeclarations/NewReturnTypeDeclarationsUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1702 Classes/NewTypedProperties: minor clean up
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
Labels: chores/QA, PR: quick merge, PR: ready for review

#1703 Classes/NewTypedProperties: bug fix - don't skip too far
  PHPCompatibility/Sniffs/Classes/NewTypedPropertiesSniff.php
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1704 Classes/NewClasses: bug fix - check all parts of a type
  PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1705 Classes/RemovedClasses: bug fix - check all parts of a type
  PHPCompatibility/Sniffs/Classes/RemovedClassesSniff.php
  PHPCompatibility/Tests/Classes/RemovedClassesUnitTest.inc
  PHPCompatibility/Tests/Classes/RemovedClassesUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1706 Interfaces/NewInterfaces: bug fix - check all parts of a type
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1709 GH Actions: work around intermittent apt-get errors
  .github/workflows/basics.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1700 Adapting namespace sensitivity from pr (#1695) to issue (#1649)
  PHPCompatibility/Sniffs/Interfaces/InternalInterfacesSniff.php
  PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.php
  PHPCompatibility/Tests/Interfaces/InternalInterfacesUsesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
  PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
  PHPCompatibility/Tests/Interfaces/NewInterfacesUsesUnitTest.inc
Labels: enhancement
