Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2024-11, with the labels that each got.

#1791 Sniff updates for upcoming "yield from" changes in PHPCS 3.11.0
  PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
  PHPCompatibility/Tests/Generators/NewGeneratorReturnUnitTest.inc
  PHPCompatibility/Tests/Generators/NewGeneratorReturnUnitTest.php
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.inc
  PHPCompatibility/Tests/Keywords/NewKeywordsUnitTest.php
Labels: phpcs cross-version compat, PR: quick merge, PR: ready for review

#1792 PHP 8.3 | :sparkles: New `PHPCompatibility.Generators.NewYieldFromComment` sniff
  PHPCompatibility/Docs/Generators/NewYieldFromCommentStandard.xml
  PHPCompatibility/Sniffs/Generators/NewYieldFromCommentSniff.php
  PHPCompatibility/Tests/Generators/NewYieldFromCommentUnitTest.inc
  PHPCompatibility/Tests/Generators/NewYieldFromCommentUnitTest.php
Labels: enhancement, PR: ready for review

#1794 README: fix some broken badges
  README.md
Labels: documentation, PR: quick merge, PR: ready for review

#1793 GH Actions: PHP 8.4 has been released
  .github/workflows/test.yml
  README.md
Labels: chores/QA, PR: quick merge, PR: ready for review

#1779 False positive about $encoding argument for mb_chr(), mb_ord() and mb_scrub().
  PHPCompatibility/Sniffs/ParameterValues/NewIconvMbstringCharsetDefaultSniff.php
  PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.inc
  PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.php
Labels: bug, PR: quick merge, PR: ready for review

#1796 GH Actions: always quote variables
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: chores/QA, PR: quick merge, PR: ready for review
