Repository PHPCompatibility/PHPCompatibility, pull requests merged in 2025-07, with the labels that each got.

#1805 Update url to HTTPS
  composer.json
Labels: documentation, PR: quick merge, PR: ready for review

#1806 Composer: raise the minimum supported PHPCS + PHPCSUtils versions + fix test failures
  PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenVariableNamesInClosureUseSniff.php
  PHPCompatibility/Sniffs/FunctionUse/NewNamedParametersSniff.php
  PHPCompatibility/Sniffs/Miscellaneous/NewPHPOpenTagEOFSniff.php
  PHPCompatibility/Tests/FunctionUse/NewNamedParametersUnitTest.inc
  PHPCompatibility/Tests/FunctionUse/NewNamedParametersUnitTest.php
  composer.json
Labels: bug, enhancement, PR: quick merge, PR: ready for review

#1798 GH Actions: use the xmllint-validate action runner and enhance checks
  .github/workflows/basics.yml
Labels: chores/QA, PR: quick merge, PR: ready for review

#1803 Ruleset file: add schema tags to the ruleset
  PHPCompatibility/ruleset.xml
  phpcs.xml.dist
Labels: chores/QA, PR: quick merge, PR: ready for review

#1810 NewLanguageConstructs: improve error messages
  PHPCompatibility/Sniffs/LanguageConstructs/NewLanguageConstructsSniff.php
  PHPCompatibility/Tests/LanguageConstructs/NewLanguageConstructsUnitTest.php
Labels: enhancement, PR: quick merge, PR: ready for review

#1811 Upgrade/LowPHP: simplify skipping the rest of the file
  PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
Labels: chores/QA, PR: quick merge, PR: ready for review
